<div class="adyen_support-main">
    <table class="adyen_support-content">
        <tr>
            <th class="adyen_support-label">Topic</th>
            <td>
                <select name="configuration_setting" id="support_topic_value">
                    <option value="">Please select a topic</option>
                    <option value="">1</option>
                    <option value="">2</option>
                    <option value="">3</option>
                    <option value="">4</option>
                    <option value="">5</option>
                    <option value="">6</option>
                </select>
            </td>
        </tr>
    </table>
</div>
