<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$titleIdHtml = ($block->getTitleId()) ? ' id="' . $block->escapeHtmlAttr($block->getTitleId()) . '"' : '';
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$title = $block->getPageTitle();
?>

<img src="<?= $block->escapeUrl($block->getViewFileUrl('Adyen_Payment::images/adyen/adyen-support.svg')) ?>"
     alt="Adyen Logo" class="adyen-support-logo" />
