<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

/**
 * @var Boleto $block
 */

use Adyen\Payment\Block\Info\Boleto;

?>

<dl class="payment-method adyen_cc">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dt class="title"><a target="_blank" href="<?= $block->escapeHtml(
        $block->getPaymentActionData('downloadUrl')
    ); ?>"><?= $block->escapeHtml(__("Click here to download Boleto PDF.")); ?></a></dt>

    <?php
        if ($block->getPartialPayments()->getSize() > 1) {
            echo $block->renderPartialPaymentsHtml();
        }
    ?>
</dl>
