<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile

?>
<?php
$_info = $block->getInfo();
?>
<dl class="payment-method adyen_cc">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dt class="title"><a target="_blank" href="<?= $block->escapeHtml(
        $block->getPaymentActionData('downloadUrl')
    ); ?>"><?= $block->escapeHtml(__("Click here to download Boleto PDF.")); ?></a></dt>

    <?php if ($block->getPartialPayments()): ?>
        <dt class="title"><b><?= $block->escapeHtml(__("Partial Payments")) ?></b></dt>
        <?php foreach ($block->getPartialPayments() as $payment): ?>
            <dt class="title">
                <?= $block->escapeHtml(sprintf("%s - %s", ucwords($payment->getPaymentMethod()), $payment->getFormattedAmountWithCurrency())) ?>
            </dt>
        <?php endforeach; ?>
    <?php endif; ?>
</dl>
