<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2022 Adyen N.V. (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile

?>
<dl class="payment-method adyen_cc">
    <dt class="title"><?= $block->escapeHtml(__('Mail/Telephone Order')) ?></dt>
    <dt class="title"><?= $block->escapeHtml(__($block->getCcTypeName())); ?></dt>
</dl>
