<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

/**
 * @var Cc $block
 */

use Adyen\Payment\Block\Info\Cc;

?>
<dl class="payment-method adyen_cc">
    <dt class="title">
        <?= $block->escapeHtml(sprintf("%s: %s", ucwords($block->getMethod()->getTitle()), __($block->getCcTypeName()))) ?>
    </dt>

    <?php
        if ($block->getPartialPayments()->getSize() > 1) {
            echo $block->renderPartialPaymentsHtml();
        }
    ?>
</dl>
