<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2023 Adyen N.V. (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile
/**
 * @var Giftcard $block
 */

use Adyen\Payment\Block\Info\Giftcard;

?>
<?php $_info = $block->getInfo(); ?>

<dl class="payment-method adyen_hpp">
    <?php if ($block->getPartialPayments()): ?>
        <dt class="title"><?= $block->escapeHtml($_info->getMethodInstance()->getTitle()); ?></dt>
        <dt class="title"><b><?= $block->escapeHtml(__("Partial Payments")) ?></b></dt>
        <?php foreach ($block->getPartialPayments() as $payment): ?>
            <dt class="title">
                <?= $block->escapeHtml(sprintf("%s - %s", ucwords($payment->getPaymentMethod()), $payment->getFormattedAmountWithCurrency())) ?>
            </dt>
        <?php endforeach; ?>
    <?php else: ?>
        <dt class="title">
            <?php
            $brandCode = $_info->getAdditionalInformation('brand_code');

            if (!empty($brandCode)) {
                $html =  sprintf("%s: %s", $_info->getMethodInstance()->getTitle(), ucwords($brandCode));
            } else {
                $html = $_info->getMethodInstance()->getTitle();
            }

            echo $block->escapeHtml($html);
            ?>
        </dt>
    <?php endif; ?>
</dl>
