<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile

?>
<dl class="payment-method adyen_cc">
    <dt class="title">
        <?= sprintf("%s: %s", $block->escapeHtml(ucwords($block->getMethod()->getTitle())), $block->escapeHtml(__($block->getCcTypeName()))) ?>
    </dt>

    <?php if ($block->getPartialPayments()): ?>
        <dt class="title"><b><?= $block->escapeHtml(__("Partial Payments")) ?></b></dt>
        <?php foreach ($block->getPartialPayments() as $payment): ?>
            <dt class="title">
                <?= sprintf("%s - %s", $block->escapeHtml(ucwords($payment->getPaymentMethod())), $block->escapeHtml($payment->getFormattedAmountWithCurrency())) ?>
            </dt>
        <?php endforeach; ?>
    <?php endif; ?>
</dl>
