<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

?>

<?php
if ($block->getRedirectMethod() == "GET") { ?>
    <body>
    <script>
        window.location.replace("<?= $block->escapeJs($block->getRedirectUrl()); ?>");
    </script>
    </body>
    <?php
} else { ?>
    <body onload="document.getElementById('3dform').submit();">
    <form method="POST" action="<?= $block->escapeHtml($block->getRedirectUrl()); ?>" id="3dform">
        <input type="hidden" name="PaReq" value="<?= $block->escapeHtml($block->getPaReq()); ?>"/>
        <input type="hidden" name="MD" value="<?= $block->escapeHtml($block->getMd()); ?>"/>
        <input type="hidden" name="TermUrl" value="<?= $block->escapeHtml($block->getTermUrl()); ?>"/>
        <noscript>
            <br>
            <br>
            <div style="text-align: center">
                <h1>Processing your 3-D Secure Transaction</h1>
                <p>Please click continue to continue the processing of your 3-D Secure transaction.</p>
                <input type="submit" class="button" value="continue"/>
            </div>
        </noscript>
    </form>
    </body>
    <?php
} ?>