<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Payment\Block\Info
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php $_info = $this->getInfo(); ?>
<?php if ($_pspReference = $block->getPspReference()):?>
<div><?php echo __('Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%1&txType=Payment" target="__blank">%1</a>', $block->escapeHtml($_info->getAdditionalInformation('pspReference')), $block->escapeHtml($_info->getAdditionalInformation('pspReference'))) ?>
</div>
<?php endif;?>


<?php if ($_specificInfo = $block->getSpecificInformation()):?>
<table class="data-table admin__table-secondary">
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <th><?php echo $block->escapeHtml($_label)?>:</th>
        <td><?php echo nl2br(implode("\n", $block->getValueAsArray($_value, true)))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?php echo $block->getChildHtml()?>
