<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<html>
    <head>
    </head>
    <body>

    <?php
        // Only redirect when the flow follows the checkout API case
        if ($block->isCheckoutAPM()) { ?>
            <script>
                window.location.replace("<?php echo $block->getRedirectUrl()?>");
            </script>
        <?php
        // Form submission for the old HPP flow
        } else { ?>
            <form id="adyen_form" method="POST" action="<?php echo $block->getFormUrl()?>">

                <?php
                foreach($block->getFormFields() as $field => $value) {
                    echo '<input type="hidden" name="' .htmlspecialchars($field,   ENT_COMPAT | ENT_HTML401 ,'UTF-8').
                        '" value="' .htmlspecialchars($value, ENT_COMPAT | ENT_HTML401 ,'UTF-8') . '" />';
                }
                ?>
            </form>
            <script>
                document.getElementById('adyen_form').submit();
            </script>
        <?php
        }
    ?>

    </body>
</html>