name: Feature request
description: Suggest an idea for this project. See open issues before requesting.
title: "[Feature]: "
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        #### Thank you for suggesting a feature! Please provide all the required information to help us evaluate your request.
        Making your own contribution is easy, encouraged, and greatly appreciated! For more info, please refer to the [contribution guidelines](https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md).

  - type: input
    id: feature-summary
    attributes:
      label: "Feature summary"
      description: "Provide a short description of the feature request."
      placeholder: "Example: Add support for donation."

  - type: textarea
    id: problem-statement
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "Explain the problem this feature aims to solve."
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Describe the solution you'd like"
      description: "Provide a clear and concise description of what you want to happen."
      placeholder: "Example: Add Donation feature to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "Provide a clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Example: I tried to... but..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context, references, or screenshots about the feature request."
      placeholder: "Example: This feature would help users by..."