<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2021 Adyen NV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

/**
 * @var $block \Adyen\Payment\Block\Form\PayByLink
 * @var $escaper \Magento\Framework\Escaper
 */

?>

<script>
    require(["jquery", "mage/calendar"],
        function ($) {
        debugger;
            $("#adyen_pbl_expires_at").calendar({
                changeYear: true,
                changeMonth: true,
                yearRange: '2010:2050',
                buttonText: 'Select Expiry Date',
                dateFormat: 'dd-mm-yy',
                minDate: new Date(<?=$escaper->escapeHtml($block->getMinExpiryDate())?>),
                maxDate: new Date(<?=$escaper->escapeHtml($block->getMaxExpiryDate())?>),
                setDate: new Date(<?=$escaper->escapeHtml($block->getDefaultExpiryDate())?>),
                defaultDate: new Date(<?=$escaper->escapeHtml($block->getDefaultExpiryDate())?>)
            });
        });
</script>

<fieldset
        class="admin__fieldset payment-method"
        id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>"
        style="display: none">
    <div class="admin__field _required">
        <label for="adyen_pbl_expires_at"
               class="admin__field-label"><span><?= $block->escapeHtml(__('Expires at')) ?></span></label>
        <div class="admin__field-control">
            <input type="text" id="adyen_pbl_expires_at" name="payment[adyen_pbl_expires_at]"
                   title="<?= $block->escapeHtml(__("Date when the payment link expires")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */
                   $block->getInfoData('adyen_pbl_expires_at') ?>"/>
        </div>
    </div>
</fieldset>