<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2021 Adyen NV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Adyen\Payment\Block\Form\PayByLink
 * @var $escaper \Magento\Framework\Escaper
 */
if (!isset($escaper)) {
    $escaper = $block;
}
?>

<?php
$minDate = $escaper->escapeHtml($block->getMinExpiryTimestamp());
$maxDate = $escaper->escapeHtml($block->getMaxExpiryTimestamp());
$defaultExpiryDate = $block->escapeJs($block->getDefaultExpiryDate());
$serverTimezone =  date(' (T)');

$scriptString = <<<script
require([
        'jquery',
        'jquery-ui-modules/widget',
        'jquery-ui-modules/datepicker',
        'jquery-ui-modules/timepicker'
    ], function ($) {
        const defaultExpiryDate = new Date($defaultExpiryDate);
        const formatExpiryDateOptions = {
            day: 'numeric',
            month: '2-digit',
            year: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
        };
        const formatedExpiryDate = defaultExpiryDate.toLocaleString('en-GB', formatExpiryDateOptions)
            .replace(/\//g, '-')
            .replace(',', '');
        $("#adyen_pbl_expires_at").datetimepicker({
            dateFormat: 'dd-mm-yy',
            timeFormat: 'HH:mm:ss',
            minDate: new Date($minDate),
            maxDate: new Date($maxDate)
        }).val(formatedExpiryDate);
    });
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<fieldset
        class="admin__fieldset payment-method"
        id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>"
        style="display: none">
    <div class="admin__field _required">
        <label for="adyen_pbl_expires_at" class="admin__field-label">
            <?= $escaper->escapeHtml(__('Payment link expires at') . $serverTimezone) ?>
        </label>
        <div class="admin__field-control">
            <input type="text" id="adyen_pbl_expires_at" name="payment[adyen_pbl_expires_at]"
                   title="<?= $escaper->escapeHtml(__("Date when the payment link will expire")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */
                   $block->getInfoData('adyen_pbl_expires_at') ?>"/>
        </div>
    </div>
</fieldset>
