<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 37px;
        height: 22px;
        vertical-align: middle;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .2s ease-in 0s;
        transition: .2s ease-in 0s;
        vertical-align: middle;
    }
    .sliderOne {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .2s ease-in 0s;
        transition: .2s ease-in 0s;
        vertical-align: middle;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: -5px;
        bottom: -1px;
        background-color: white;
        -webkit-transition: .2s ease-in 0s;
        transition: .2s ease-in 0s;
        vertical-align: middle;
    }

    .sliderOne:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: 0px;
        bottom: -1px;
        background-color: white;
        -webkit-transition: .2s ease-in 0s;
        transition: .2s ease-in 0s;
        vertical-align: middle;
    }

    input:checked + .slider {
        background-color: #79a22e;
    }

    input:focus + .slider {
        box-shadow: 0 0 0px #2196F3;
    }

    input:checked + .sliderOne {
        background-color: #79a22e;
    }

    input:focus + .sliderOne {
        box-shadow: 0 0 0px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(18px);
        -ms-transform: translateX(18px);
        transform: translateX(18px);
    }
    input:checked + .sliderOne:before {
        -webkit-transform: translateX(18px);
        -ms-transform: translateX(18px);
        transform: translateX(18px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 35px;
        border: 1px solid #ccc;
    }

    .slider.round:before {
        border-radius: 100%;
        display: inline-block;
        border: 1px solid #ccc;
    }

    .sliderOne.round {
        border-radius: 35px;
        border: 1px solid #ccc;
    }

    .sliderOne.round:before {
        border-radius: 100%;
        display: inline-block;
        border: 1px solid #ccc;
    }

    .tooltip-toggle {
        position: relative;
        right: -2rem;
    }

    .toggle-cell {
        display: flex;
        justify-content: space-between
    }
</style>

<?php $randomId = rand(); ?>
<?php $groupName = $this->getGroupName(); ?>
<?php $fieldName = $this->getFieldName(); ?>
<?php $realData = (int)$this->getMyStatus(); ?>

<script>
    function toggleFunction(randomId) {
        if(document.getElementById(randomId).checked) {
            document.getElementById(randomId).nextElementSibling.setAttribute("class","sliderOne round");
            // document.getElementById(randomId).value = '1'
        }else{
            document.getElementById(randomId).nextElementSibling.setAttribute("class","slider round");
            // document.getElementById(randomId).value = '0'
        }
    }
</script>

<label class="switch" >
<!--    <input value="0" type="hidden" name="--><?php //echo $groupName; ?><!--" >-->
    <input value="0" type="checkbox" id="<?php echo 'input-' . $randomId; ?>" name="<?php echo $groupName; ?>" onclick="toggleFunction('<?php echo "input-" . $randomId ?>')" <?= $realData ? 'checked' : '' ?>>
    <span class="<?= $realData ? 'sliderOne' : 'slider' ?> round" id="<?php echo 'span-' . $randomId; ?>" ></span>
</label>

