<?php $randomId = rand(); ?>
<?php $groupName = $this->getGroupName(); ?>
<?php $fieldName = $this->getFieldName(); ?>
<?php $inputFieldName = "groups[".$groupName."][fields][".$fieldName."][value]"; ?>

<script>
    function toggleFunction(randomId) {
        if(document.getElementById(randomId).classList.contains("slider")) {
            document.getElementById(randomId).setAttribute("class","sliderOne round");
            document.getElementById(randomId).checked = true;
        }else{
            document.getElementById(randomId).setAttribute("class","slider round");
            document.getElementById(randomId).checked = false;
        }
    }
</script>

<label class="switch" >
    <input type="checkbox" onclick="toggleFunction('<?php echo "spa-" . $randomId ?>')" name="<?php echo $inputFieldName; ?>" >
    <span class="slider round" id="<?php echo 'spa-' . $randomId; ?>" ></span>
</label>

<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 37px;
        height: 22px;
        vertical-align: middle;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }
    .sliderOne {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: -5px;
        bottom: -1px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }

    .sliderOne:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: 0px;
        bottom: -1px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
        vertical-align: middle;
    }

    input:checked + .slider {
        background-color: #79a22e;
    }

    input:focus + .slider {
        box-shadow: 0 0 0px #2196F3;
    }

    input:checked + .sliderOne {
        background-color: #79a22e;
    }

    input:focus + .sliderOne {
        box-shadow: 0 0 0px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(20px);
        -ms-transform: translateX(20px);
        transform: translateX(20px);
    }
    input:checked + .sliderOne:before {
        -webkit-transform: translateX(20px);
        -ms-transform: translateX(20px);
        transform: translateX(20px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 35px;
        border: 1px solid #ccc;
    }

    .slider.round:before {
        border-radius: 100%;
        display: inline-block;
        border: 1px solid #ccc;
    }

    .sliderOne.round {
        border-radius: 35px;
        border: 1px solid #ccc;
    }

    .sliderOne.round:before {
        border-radius: 100%;
        display: inline-block;
        border: 1px solid #ccc;
    }

</style>