name: "Static tests for Adyen Magento 2 payment plugin"
description: "This action triggers the static tests flow"

runs:
  using: "composite"
  steps:
    - name: Install Magento
      run: docker compose -f .github/docker-compose.yml run --rm web make magento
      env:
        PHP_VERSION: "8.3"
        MAGENTO_VERSION: "2.4.8-p2"
        DEPLOY_SAMPLEDATA: 1

    - name: Start web server in background
      run: docker compose -f .github/docker-compose.yml up -d web

    - name: Setup permissions
      run: docker exec magento2-container make fs

    - name: Check install
      run: docker exec magento2-container make sys-check

    - name: Install plugin
      run: docker exec -u www-data magento2-container make plugin
      env:
        ADYEN_API_KEY: ${{ secrets.ADYEN_API_KEY }}
        ADYEN_CLIENT_KEY: ${{ secrets.ADYEN_CLIENT_KEY }}
        ADYEN_MERCHANT: ${{ secrets.ADYEN_MERCHANT }}
        ADMIN_USERNAME: ${{ secrets.MAGENTO_ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.MAGENTO_ADMIN_PASSWORD }}
        DONATION_ACCOUNT: ${{ secrets.DONATION_ACCOUNT }}

    - name: Kill Cron Jobs
      run: docker exec magento2-container /etc/init.d/cron stop

    - name: Run PHPUnit
      run: docker exec magento2-container make phpunit-run
