<script>
    require([
            'jquery',
            'prototype'
        ],
        function(jQuery)
        {
            var progressSpan = jQuery('#progress');

            jQuery('#adyen_configure_merchants').click(function ()
            {
                jQuery('#adyen_payments_configuration_errors').hide();
                var params = {};
                new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                    parameters:     params,
                    loaderArea:     false,
                    asynchronous:   true,
                    onCreate: function() {
                        progressSpan.find('.configured').hide();
                        progressSpan.find('.processing').show();
                        jQuery('#adyen_payments_configured_message').text('');
                        document.getElementById("adyen_configure_merchants").disabled = true;
                    },
                    onSuccess: function (response) {
                        //add html response
                        progressSpan.find('.processing').hide();
                        var clientkey = response.responseJSON.messages.clientKey;
                        var resultText = '';
                        if (response.status > 200) {
                            resultText = response.statusText;
                        } else {
                            var merchantAccountSelect = document.getElementById(
                                "payment_us_adyen_group_all_in_one_adyen_required_settings_merchant_account");
                            //remove previous accounts
                            var i, L = merchantAccountSelect.options.length - 1;
                            for(i = L; i >= 0; i--) {
                                merchantAccountSelect.remove(i);
                            }
                            //add the merchant accounts to the html element
                            var accounts = response.responseJSON.messages.associatedMerchantAccounts;
                            for (i = 0; i < accounts.length; i++) {
                                merchantAccountSelect.add( new Option(accounts[i],accounts[i]));
                            }
                            //add the clientkey
                            if (response.responseJSON.mode == 'test') {
                                var clientKeyIdTest = document.getElementById(
                                    'payment_us_adyen_group_all_in_one_adyen_required_settings_client_key_test');
                                clientKeyIdTest.value = clientkey;
                            }
                            elseif(response.responseJSON.mode == 'production')
                            {
                                var clientKeyIdLive = document.getElementById(
                                    'payment_us_adyen_group_all_in_one_adyen_required_settings_client_key_live');
                                clientKeyIdLive.value = clientkey;
                            }
                            resultText = 'Completed';
                            progressSpan.find('.configured').show();
                        }
                        var configurationErrors = document.getElementById(
                            'adyen_payments_configuration_errors');
                        configurationErrors.value = resultText;
                    },
                    onFailure: function(response)
                    {
                        progressSpan.find('.processing').hide();
                        jQuery('#adyen_payments_configured_message').text("Failed");
                    },
                    onComplete: function()
                    {
                        document.getElementById("adyen_configure_merchants").disabled = false;
                    }
                });
            });

        });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="adyen-required-settings-config-admin" id="progress">
    <img class="processing" hidden="hidden" alt="Configuring" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="configured" hidden="hidden" alt="Configured" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="adyen_payments_configured_message"></span>
    <div id="adyen_payments_configuration_errors" class="message-system-inner">
        <div class="message message-warning"></div>
    </div>
</span>
<!--if we want to add a note under the button-->
<p class="note">
    <span><?php echo __(''); ?></span>
</p>
