<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<body onload="document.getElementById('3dform').submit();">
<form method="POST" action="<?php echo $block->getIssuerUrl(); ?>" id="3dform">
    <input type="hidden" name="PaReq" value="<?php echo $block->getPaReq(); ?>" />
    <input type="hidden" name="MD" value="<?php echo $block->getMd() ?>" />
    <input type="hidden" name="TermUrl" value="<?php echo $block->getTermUrl(); ?>" />
    <noscript>
        <br>
        <br>
        <div style="text-align: center">
            <h1>Processing your 3-D Secure Transaction</h1>
            <p>Please click continue to continue the processing of your 3-D Secure transaction.</p>
            <input type="submit" class="button" value="continue"/>
        </div>
    </noscript>
</form>
</body>