<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2021 Adyen N.V. (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

// @codingStandardsIgnoreFile
/**
 * @var Adyen\Payment\Block\Form\Cc $block
 * @var $escaper \Magento\Framework\Escaper
 */
$code = $escaper->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */
          $code; ?>">
    <span id="noClientKey"
          class="message message-error error"
          style="display: none"><?= $escaper->escapeHtml(
            __(
                'Please configure a Client key and a live endpoint prefix (if in Production Mode) in your Adyen ' .
                'Required Settings'
            )
        ); ?>
    </span>
    <input name="payment[stateData]" id="adyen-cc-statedata" type="hidden">
    <div id="cardContainer-<?= /* @noEscape */
    $code; ?>"></div>

    <script>
        require(
            [
                'jquery',
                'Adyen_Payment/js/bundle'
            ],
            function ($) {
                var ccTypes = <?= /* @noEscape */ json_encode($block->getCcAvailableTypesByAlt()); ?>;

                // Get cc type by adyen cc type
                var getCcCodeByAltCode = function (altCode) {

                    if (ccTypes.hasOwnProperty(altCode)) {
                        return ccTypes[altCode];
                    }

                    return "";
                }

                if (!"<?= $block->getClientKey(); ?>") {
                    document.getElementById('noClientKey').style = "visibility: visible; display:inline-block";
                    return;
                }
                var cardNode = document.getElementById("cardContainer-<?= /* @noEscape */ $code; ?>");

                var checkout = new AdyenCheckout({
                    clientKey: "<?= /* @noEscape */ $block->getClientKey(); ?>",
                    environment: "<?= /* @noEscape */ $block->getCheckoutEnvironment(); ?>",
                    locale: "<?= /* @noEscape */ $block->getLocale(); ?>",
                    risk: {
                        enabled: <?= /* @noEscape */ json_encode($block->getEnableRisk());?>
                    }
                });
                try {
                    var card = checkout.create('card', {
                        brands: Object.keys(ccTypes),
                        hideCVC: <?= /* @noEscape */ json_encode(!$block->hasVerification()); ?>,
                        hasHolderName: <?= /* @noEscape */ json_encode($block->getHasHolderName());?>,
                        holderNameRequired: <?= /* @noEscape */ json_encode($block->getHolderNameRequired());?>,
                        enableStoreDetails: <?= /* @noEscape */ json_encode($block->getEnableStoreDetails());?>,
                        installmentOptions: <?= /* @noEscape */ $block->getFormattedInstallments();?>,
                        showInstallmentAmounts: true,
                        onChange: function (state) {
                            if (state.isValid) {
                                $('#adyen-cc-statedata').val(JSON.stringify(state.data)).removeAttr('disabled');
                            }
                        }
                    });
                    card.mount(cardNode);
                } catch (e) {
                    console.log(e);
                }
            });
    </script>
</fieldset>
