<?php
/**
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2021 Adyen N.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<!-- ko template: getTemplate() --><!-- /ko -->
<script>
    require([
        'uiLayout',
        'jquery',
        'Adyen_Payment/js/model/adyen-payment-service'
    ], function (layout, $, adyenPaymentService) {
        $(function () {

            let allowedPaymentMethods = [
                // 'amazonpay',
                // 'applepay',
                // 'bcmc_mobile',
                // 'boleto',
                // 'dotpay',
                // 'facilypay_3x',
                // 'googlepay',
                'ideal',
                'klarna',
                // 'multibanco',
                // 'paypal'
            ];

            // TODO after ECP-8516
            // let paymentMethodsObserver = adyenPaymentService.getPaymentMethods();
            // paymentMethodsObserver.subscribe(
            //     function(paymentMethodsResponse) {
            //         let filteredPaymentMethods = paymentMethodsResponse.paymentMethodsResponse.paymentMethods.filter(paymentMethod => {
            //             return allowedPaymentMethods.includes(paymentMethod.type);
            //         });

                    let layoutConfigurations = [];

            allowedPaymentMethods.forEach((paymentMethod) => {
                        let paymentMethodData = {
                            method: `adyen_${paymentMethod}`
                        };

                        layoutConfigurations.push({
                            component: `Adyen_Payment/js/view/payment/method-renderer/multishipping/adyen-${paymentMethod}-method`,
                            name: `payment_method_adyen_${paymentMethod}`,
                            method: paymentMethodData.method,
                            item: paymentMethodData
                        });
                    })

                    layout(layoutConfigurations);
                    $('body').trigger('contentUpdated');
                // }
            // );
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
