<?php
/**
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2021 Adyen N.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<!-- ko template: getTemplate() --><!-- /ko -->
<script>
    require([
        'uiLayout',
        'jquery',
        'Adyen_Payment/js/model/adyen-payment-service'
    ], function (layout, $, adyenPaymentService) {
        $(function () {

            let pmResponse = ['klarna', 'ideal'];

            let paymentmeths = adyenPaymentService.retrievePaymentMethods().done(
                response => console.log('rok was here: ', response);
        )

            pmResponse.map((paymentMethod) => {
                    let paymentMethodData = {
                        method: `adyen_${paymentMethod}`
                    };

                    layout([
                        {
                            component: `Adyen_Payment/js/view/payment/method-renderer/multishipping/adyen-${paymentMethod}-method`,
                            name: `payment_method_adyen_${paymentMethod}`,
                            method: paymentMethodData.method,
                            item: paymentMethodData

                        }
                    ]);
                    $('body').trigger('contentUpdated');
                })
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
