<?php
/**
 *
 * Adyen Payment Module
 *
 * Copyright (c) 2021 Adyen N.V.
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more info.
 *
 * Author: Adyen <magento@adyen.com>
 */
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'adyen_klarna'
            };
            layout([
                {
                    component: 'Adyen_Payment/js/view/payment/method-renderer/multishipping/adyen-klarna-method',
                    name: 'payment_method_adyen_klarna',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);
            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
