<?php declare(strict_types=1);

/**
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2022 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */
namespace Adyen\Payment\Tests\Unit;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

abstract class AbstractAdyenTestCase extends TestCase
{
    public function getSimpleMock($originalClassName, array $additionalMethods = []): MockObject
    {
        $mockBuilder = $this->getMockBuilder($originalClassName);

        if (!empty($additionalMethods)) {
            $mockBuilder = $mockBuilder->addMethods($additionalMethods);
        }

        return $mockBuilder->disableOriginalConstructor()->getMock();
    }

    /**
     * Mock a class dynamically generated by Magento
     */
    protected function createGeneratedMock(string $originalClassName, array $additionalMethods = []): MockObject
    {
        return $this->getMockBuilder($originalClassName)
            ->setMethods($additionalMethods)
            ->disableOriginalConstructor()
            ->disableOriginalClone()
            ->disableArgumentCloning()
            ->getMock();
    }
}
