<?php
/**
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2023 Adyen N.V. (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

use Adyen\Payment\Block\Info\Giftcard;

/**
 * @see \Magento\Payment\Block\Info
 * @var Giftcard $block
 */
// @codingStandardsIgnoreFile
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()); ?>

<?php
$_info = $block->getInfo();
$_isDemoMode = $block->isDemoMode();
?>

<?php if ($block->getPartialPayments()): ?>
    <p style="margin-top: 10px"><b>Partial Payments</b></p>
    <table class="edit-order-table" style="text-align:left; margin-top:5px; margin-bottom:0;" aria-describedby="Partial Payments">
        <tr>
            <th scope="col">PspReference</th>
            <th scope="col">Payment Method</th>
            <th scope="col">Amount</th>
            <th scope="col">Refunded</th>
            <th scope="col">Captured</th>
        </tr>
        <?php foreach ($block->getPartialPayments() as $payment): ?>
            <tr>
                <td>
                    <?php if ($_isDemoMode): ?>
                        <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=<?= $block->escapeHtml(
                            $payment->getPspreference()
                        ); ?>&txType=Payment" target="_blank"><?= $block->escapeHtml($payment->getPspreference()); ?></a>
                    <?php else: ?>
                        <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=<?= $block->escapeHtml(
                            $payment->getPspreference()
                        ); ?>&txType=Payment" target="_blank"><?= $block->escapeHtml($payment->getPspreference()); ?></a>
                    <?php endif; ?>
                </td>
                <td><?= $block->escapeHtml($payment->getPaymentMethod()); ?></td>
                <td><?= $block->escapeHtml($payment->getFormattedAmountWithCurrency()); ?></td>
                <td><?= $block->escapeHtml($payment->getFormattedTotalRefundedWithCurrency()); ?></td>
                <td><?= $block->escapeHtml($payment->getFormattedTotalCapturedWithCurrency()); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <?php if ($_pspReference = $_info->getAdditionalInformation('pspReference')): ?>
        <div>
            <?php if ($_isDemoMode): ?>
                <?= $block->escapeHtml(__('Adyen PSP Reference: ')); ?>
                <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=<?= $block->escapeHtml(
                    $_pspReference
                ); ?>&txType=Payment" target="_blank"><?= $block->escapeHtml($_pspReference); ?></a>
            <?php else: ?>
                <?= $block->escapeHtml(__('Adyen PSP Reference: ')); ?>
                <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=<?= $block->escapeHtml(
                    $_pspReference
                ); ?>&txType=Payment" target="_blank"><?= $block->escapeHtml($_pspReference); ?></a>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php /** TODO:: ECP-9636 Indicate the gift card brand on single gift card payments (ie: METHOD_TITLE: SVS) */ ?>
<?php endif; ?>

<?= $block->escapeHtml($block->getChildHtml()); ?>
