<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2018 Adyen BV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

/** @var \Adyen\Payment\Block\Info\PaymentLink $block */
?>
<br />
<div class="admin__page-section-item-title">
    <span class="title"><?php echo __('Adyen Payment Link');?></span>
</div>
<a href="<?=$block->getPaymentLinkUrl();?>" target="_blank">
    <?php echo __('Adyen Payment Link for remaining total due'); ?>
</a>
