<?php
/**
 *                       ######
 *                       ######
 * ############    ####( ######  #####. ######  ############   ############
 * #############  #####( ######  #####. ######  #############  #############
 *        ######  #####( ######  #####. ######  #####  ######  #####  ######
 * ###### ######  #####( ######  #####. ######  #####  #####   #####  ######
 * ###### ######  #####( ######  #####. ######  #####          #####  ######
 * #############  #############  #############  #############  #####  ######
 *  ############   ############  #############   ############  #####  ######
 *                                      ######
 *                               #############
 *                               ############
 *
 * Adyen Payment module (https://www.adyen.com/)
 *
 * Copyright (c) 2021 Adyen NV (https://www.adyen.com/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>
 */

/**
 * @var $block \Adyen\Payment\Block\Form\PayByLink
 * @var $escaper \Magento\Framework\Escaper
 */

?>
info/pbl
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>">
    <!--div class="admin__field _required">
        <label for="po_number" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Purchase Order Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="po_number" name="payment[po_number]"
                   title="<?= $block->escapeHtml(__("Purchase Order Number")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */
    $block->getInfoData('po_number') ?>"/>
        </div>
    </div-->
</fieldset>